theme: story
baseurl: /
title: Origins of Aneuploidy Research Consortium
paginate: 50
buildFuture: yes
menu:
  main:
    - name: About
      title: About
      url: /about
      weight: 1
    - name: Members
      title: Members
      url: /
      weight: 2
    - name: Meetings
      title: Meetings
      url: /meetings
      weight: 3
    - name: Publications
      title: Publications
      url: /publications
      weight: 4
    - name: News
      title: News
      url: /news
      weight: 5
    - name: Contact
      title: Contact
      url: /contact
      weight: 6
params:
  author: Origins of Aneuploidy Research Consortium |  P.O. Box 570, Flanders, NJ 07836-9998
  classes: []
  enableMobileMenu: true
outputs:
  home:
    - HTML
    - JSON
    - RSS
  page: HTML
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML
    - RSS


#[markup]
#  [markup.goldmark]
#    [markup.goldmark.renderer]
#      unsafe = true
